# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion_Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=11)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Capa')),
                ('codicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Condicion')),
            ],
        ),
        migrations.CreateModel(
            name='Condicion_Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorComparar', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=11)),
                ('codicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Condicion')),
            ],
        ),
        migrations.CreateModel(
            name='DataImage_Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Capa')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(default='images/none_image.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.TipoCampo'),
        ),
        migrations.AddField(
            model_name='image',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Proyecto'),
        ),
        migrations.AddField(
            model_name='dataimage_indicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Indicador'),
        ),
        migrations.AddField(
            model_name='condicion_indicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Indicador'),
        ),
        migrations.AddField(
            model_name='capa',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardConfigApp.Image'),
        ),
    ]
